### ISSUE TITLE
[WISE FR]: renaming tasks

### ISSUE THREAD

**Issue by RobBryce** [WISE-Developers/Project_issues#125]
### Contact Details

rbryce@heartlandsoftware.ca

### What is needed?

The source trees should be scanned and all references to PSaaS should be changed to WISE.  (Or W.I.S.E.).  Executables should be renamed.  Any documentation, etc. needs updated.  I'm not sure about any URL's.

We also need a new logo and credits detail for projects using PSaaS->WISE, for proper accreditation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@nealmcloughlin @BadgerOnABike If you think of any other renaming/rebranding issues, please add them here for now.

**Comment by RobBryce** [comment]
Other:
Copyright notices and dates in the source tree (and who is the copyright assigned to)?
Potentially names of target executables (WISE.EXE)?  Should probably review names of DLL's to avoid conflict with any Prometheus co-install.

**Comment by spydmobile** [comment]
> Other: Copyright notices and dates in the source tree (and who is the copyright assigned to)? 

All code will remain copyright of the project because we will use use a contribution agreement to require assignment of contributions as we all discussed previously.
I would prefer : @copyright (Year of ver 1 release) - Current Year then Project name so eg:
&copy; 2022-2023 The WISE Project Team

> Potentially names of target executables (WISE.EXE)?
 
Yes!

> Should probably review names of DLL's to avoid conflict with any Prometheus co-install. 

Agreed!
