### ISSUE TITLE
[WISE Bug]: Linux WISE on Azure & Windows 10 WSL

### ISSUE THREAD

**Issue by RobBryce** [WISE-Developers/Project_issues#154]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

Reported issues with W.I.S.E. on Azure.

### Version

(Linux) 2021.11.xx

### What component are you seeing the problem on?

WISE Binary

### Relevant log output

From Alex: On Azure - Directly inside the container, running ```psaas --validate job.fgmj ``` leads to the following error:
```
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  Invalid argument
/usr/bin/psaas: line 2:  6688 Aborted                 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/psaas /usr/lib/psaas/psaas "$@"
```

From Alex: Windows 10 Enterprise 20H2 OS build 19042.2251. My WSL distro is Ubuntu 22.04.1 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)
```
2022-12-16 16:01:25 WISE-DEMO-DEVELOPER  | 
2022-12-16 16:01:25 WISE-DEMO-DEVELOPER  | > base_typescript@1.0.0 model
2022-12-16 16:01:25 WISE-DEMO-DEVELOPER  | > node dist/model.js
2022-12-16 16:01:25 WISE-DEMO-DEVELOPER  | 
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | Clearing old results
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | Running the job
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | error: Command failed: /usr/bin/psaas ~/app_data/testjob/job.fgmj
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  |   what():  Failed to load CPU details.
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | /usr/bin/psaas: line 2:    30 Aborted                 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/psaas /usr/lib/psaas/psaas "$@"
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | 
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | error: Command failed: /usr/bin/psaas ~/app_data/testjob/job.fgmj --validate
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  |   what():  Invalid argument
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | /usr/bin/psaas: line 2:    27 Aborted                 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/psaas /usr/lib/psaas/psaas "$@"
2022-12-16 16:01:26 WISE-DEMO-DEVELOPER  | 
```

### Approvals Process

- [ ] Testing For Issue
- [ ] Executive Approval
- [ ] Merge

**Comment by RobBryce** [comment]
Travis reports that W.I.S.E. for Linux is compiled against Ubuntu 20.04. The latest WSL uses Ubuntu 22. Some of Azure’s web app services are also Ubuntu 22.

**Comment by RobBryce** [comment]
Travis also reports: Also with some form of bastardized Linux kernel which may be affecting shared memory usage (judging by the error messages, I don’t know what exactly they’ve modified).  Initial thoughts are that the issue is with W.I.S.E. failing on the shared memory region that is used so that multiple instances use different CPU cores/threads.

**Comment by RobBryce** [comment]
We don’t know what the effect of running W.I.S.E. in a container on a system that is not Ubuntu 20 will be. The container is a thin client within the host OS so low level hooks could still be trying to call the host kernel which may not be compatible.

**Comment by RobBryce** [comment]
So, there's multiple possible failure points: custom OS kernel that may have impacted shared memory and/or query & control over NUMA nodes, different version of the OS.  Is it possible to use the Windows version of W.I.S.E.?

**Comment by RobBryce** [comment]
Also, it's worth mentioning here that 1.5 months of time spent with experts at Oracle showed us that this EXE works best closest to the hardware.  Any kind of hardware abstraction where we loose access or control over NUMA nodes and core assignment is going to hurt performance and very quickly.  Any HAL that moves the process around is going to further have unknown effects.  This information was expected but confirmed over tests.  Before that, we also tested extensively on Azure and AWS, which is why we currently run the backbone infrastructure in those frameworks, but run the computations on hardware.  When looking at the cost/performance point, you also end up going to hardware, too.
Also of note, we fine-tuned a lot of the thread communication for Windows and hardware from 15 years ago.  We have not spent any time to fine-tune it for modern hardware or Linux (other than to choose the number of threads per process).

**Comment by spydmobile** [comment]
The objective is platform agnostic, and we accept that performance may suffer to do this, that cannot and wont be a sticking point. a slow agnostic version for release is better than a fast one that wont run everywhere.  Wise needs to run on linux, not ubuntu, so lets start moving in that direction. so far we can run on one old flavor of linux, now lets make it work in the obvious ones that are used everyday in the enterprise like alpine,  RedHat, CentOs and current versions/ flavors of linux and in containers on container systems.

**Comment by spydmobile** [comment]
From Alex: On Azure - Directly inside the container, running ```psaas --validate job.fgmj ``` leads to the following error:
```
terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  Invalid argument
/usr/bin/psaas: line 2:  6688 Aborted                 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/psaas /usr/lib/psaas/psaas "$@"
```

**Comment by spydmobile** [comment]
Currently @spydmobile is working with the CFS to replicate the Azure Environment, so that this issue can be replicated/tested by @RobBryce

**Comment by spydmobile** [comment]
@algodbout has provided @spydmobile with the Azure configuration details, which have been replicated. Access credentials to this Azure instance with WISE 2022-03-01 installed have been provided to @RobBryce to use for the completion of his analysis. Reassigned to @RobBryce

**Comment by tredpath** [comment]
Tested the Ubuntu 20.04 build of [2023.1.6](https://github.com/WISE-Developers/WISE_Application/releases/tag/w7.2023.1.6) on the provided Azure container. If shared memory is enabled it will still crash the same as it did previously as Azure blocks usage of shared memory. Using the -i command line switch to disable shared memory in the W.I.S.E. executable a test FGM was successfully run to completion.

**Comment by spydmobile** [comment]
@tredpath and @RobBryce this is great however, this would only help people who are executing wise directly in an azure environment. I think this needs to be an option in the JSAPI so that those of us that start wise with the API (Including Alexander and Firehawk) can leverage the workaround. If you have already done this, please disregard and reassign back to me.

**Comment by RobBryce** [comment]
The '-i' option was described in #155 .

We first tried putting compute machine configuration details (like # cores, etc.) into the API and proto definitions, then took them back out in V2 (discussed) so that the client building the FGMJ didn't have to be aware of the (changing) target environment running or re-running the FGMJ.  Manager plays a role here, too.  That's why #155 didn't suggest any proto or JSON changes.

**Comment by spydmobile** [comment]
@RobBryce Thanks, clearly #155 already says this, however, #155 does not describe the implementation, only the request. Someone needs to explain, either here, or in #155 how to enable -i via the JSAPI so that it can now be tested.

**Comment by RobBryce** [comment]
#155 comments how the -i flag changed meaning (logic was inverted to where the shared memory region will be used if -i is present, otherwise shared memory isn't used).

As mentioned above and in #155, control over the -i feature isn't appropriate for an API, since it's strictly a command line option that needs to be applied before opening the FGMJ file.

I don't know why this was changed from Don to Last Minute, since we tested and it ran on Azure, with the default operation being to not use shared memory.
