### ISSUE TITLE
[TASK] WISE: Licence for Installer

### ISSUE THREAD

**Issue by spydmobile** [WISE-Developers/Project_issues#159]
Rob indicated he wanted a version of the licence for WISE to put into the installer.

The licence we are going to use can be found here:
https://github.com/WISE-Developers/Project_issues/blob/main/LICENSE

@BadgerOnABike and @nealmcloughlin if you have concerns about this, please indicate that here.

**Comment by BadgerOnABike** [comment]
No issues here.
