### ISSUE TITLE
Windows installer defaults to Prometheus folder.

### ISSUE THREAD

**Issue by krowbar** [WISE-Developers/Project_issues#166]
It might be because I already have Prometheus installed, but a different default folder would be nice (I would guess WISE).

**Comment by spydmobile** [comment]
as discussed with @RobBryce, we need it to just install the new WISE way - in a wise folder and not do any of that old Prometheus business.

**Comment by spydmobile** [comment]
@BadgerOnABike can you please install the latest wise windows and confirm that this bug is fixed? just test, comment here on the results and assign back to me. If it passes, remove the NEEDS TESTING label please. Thanks!

**Comment by spydmobile** [comment]
@BadgerOnABike please confirm that WISE no longer tries to install to the Prometheus Folder.
I think you just tested/commented here for #60 - I can close that too if you feel it is fixed but the go-no-go for this #166 is if it tries to install wise to a prometheus folder or not.

**Comment by BadgerOnABike** [comment]
Prometheus was completely absent from anything installed, during installation and during config script. Everything is going to the WISE folder now.
