### ISSUE TITLE
[REDapp Bug]: REDApp is not open source

### ISSUE THREAD

**Issue by spydmobile** [WISE-Developers/Project_issues#168]
### What happened?

For some reason, even though HSS did the work to make it possible, We did not open up the repo. We should check in with HSS to make sure they will sign off on opening up the repo, then make REDApp open source.

### Version

(Release) 2022.03.xx

### Approvals Process

- [x] Sign Off from HSS
- [x] Wait for #167 to be resolved [![Maven Publish](https://github.com/WISE-Developers/REDapp/actions/workflows/maven-publish.yml/badge.svg)](https://github.com/WISE-Developers/REDapp/actions/workflows/maven-publish.yml)
- [x] Trigger the Jan build of REDApp
- [x] Open Up the Repo - Open Source

**Comment by spydmobile** [comment]
@RobBryce I would like to open the redapp repo, can you please discuss with your team and if you guys are ready Ill open it, and close this.

**Comment by RobBryce** [comment]
I'm not sure why it's been left closed, honestly.  I believe that all the source has the appropriate licenses to go open, and has been that way for a while now.

**Comment by spydmobile** [comment]
@RobBryce Super. If you have something in there to clean up, you will want to do it, soon cuz ill open that repo this week!
