### ISSUE TITLE
[WISE Bug]: `index.js` exports the content of `wiseInterface` as `psaas` in WISE JS API

### ISSUE THREAD

**Issue by algodbout** [WISE-Developers/Project_issues#185]
### What happened?

The `index.js` file as an export named `psaas` for the content of `wiseInterface`: https://github.com/WISE-Developers/WISE_JS_API/blob/1.0.5-beta/index.js#L10. However, its associated `index.d.ts` exports `wiseInterface` as `wise`: https://github.com/WISE-Developers/WISE_JS_API/blob/1.0.5-beta/index.d.ts#L7.

When trying to use the `wise` export as defined in the `index.d.ts`, the following error appears at runtime: `Cannot read properties of undefined (reading 'WISE')`.

When trying to use the `psaas` export as defined in the `index.js`, the program runs properly but TypeScript emits the following error: `error TS2339: Property 'psaas' does not exist on type 'typeof import("project-folder/node_modules/wise-js-api/index")'`.

### Version

(Ubuntu 2022) v1.0.0-beta

### What component are you seeing the problem on?

JS Api

### Approvals Process

- [ ] Testing For Issue
- [ ] Executive Approval
- [ ] Merge

**Comment by algodbout** [comment]
I confirm the issue has been fixed with WISE-Developers/WISE_JS_API#12. I can properly use the `wise` export in TypeScript and JavaScript.

**Comment by spydmobile** [comment]
Thank you @algodbout ! Closing this.
