### ISSUE TITLE
PSaaS Project Versions

### ISSUE THREAD

**Issue by RobBryce** [WISE-Developers/Project_issues#51]
### Contact Details

rbryce@heartlandsoftware.ca

### What is needed?

Follow-up on #21 

The depth of dependencies among projects is pretty large.  When the build of one project is dependent on another, there's many points of failure in the build tree.

With a non-automated build, all version numbers are synchronized so that any component can be identified as compatible with any other component.

In an automated build, it's possible for (e.g.) the first half of projects to build successfully and auto-increment build #'s, then a failure is introduced where subsequent project version numbers are not auto-incremented.  This can create a situation where (e.g.) different DLL's that are compatible with each other and built at the same time have a different version numbers.

An alternative is a versions repository that is used by all version numbers, and that is not auto-incremented (in the same manner).

We need direction on how to manage version numbers of PSaaS components in an automated build environment which considers automated monthly, feature test builds, and release candidates.

The versioning required is detailed in #162

**Comment by spydmobile** [comment]
I think we should adapt our version numbers to work with the github automation process, and implement it in the WISE build
