### ISSUE TITLE
[PSaaS Bug]: Windows Installer Contents

### ISSUE THREAD

**Issue by RobBryce** [WISE-Developers/Project_issues#60]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

The Windows installer for PSaaS includes Prometheus.  For V6 of the product (now only for validation purposes), this is okay.  But the V7 installer should not include Prometheus V7, which is broken and is only used for internal testing and R&D.  The installer should be limited to PSaaS and REDApp.

### Version

(Windows) 2021.12.xx

### What component are you seeing the problem on?

Other (indicate in "What happened" above)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RobBryce** [comment]
This is straightforward work.

**Comment by spydmobile** [comment]
@nealmcloughlin will need to test this when the build is complete.

**Comment by spydmobile** [comment]
I will test this when I have a dev build.

**Comment by spydmobile** [comment]
Actually, lets get @BadgerOnABike to test this as he is on windows and I am not LOL

**Comment by BadgerOnABike** [comment]
Defaults to the WISE folder now.

**Comment by BadgerOnABike** [comment]
Apologies, I'm that guy. Found some errors as I was obviously on autopilot

![image](https://user-images.githubusercontent.com/10979751/217952223-00bd8ec2-64e5-4b77-818e-f656bfeb8ae1.png)
These are unnecessary in this system.
![image](https://user-images.githubusercontent.com/10979751/217952386-96e59656-9449-4cc1-bef0-021b927b97a2.png)

![image](https://user-images.githubusercontent.com/10979751/217952452-90435782-9ce8-4b13-8f9f-7a2de525ad0d.png)

This is not the current branding.

**Comment by spydmobile** [comment]
@BadgerOnABike TAG! Your it!

**Comment by BadgerOnABike** [comment]
Branding has been updated. Does this meet the spec you'd like to see Franco?

![image](https://user-images.githubusercontent.com/10979751/218578873-c7b78783-2555-4ff0-bb38-02ca29257f42.png)

**Comment by spydmobile** [comment]
Perfect, thank you @BadgerOnABike , @RobBryce closing this.
