### ISSUE TITLE
[TASK] Revise and provide GNWT Intellifire Logo to Rob

### ISSUE THREAD

**Issue by spydmobile** [WISE-Developers/Project_issues#70]
provide rob a new logo for Intellifire

**Comment by spydmobile** [comment]
Here is the current Intellifire Logo
![intellifire_logo](https://user-images.githubusercontent.com/1065978/165636549-7affde4d-5fe8-4b74-be39-ce3f1e8c72b5.png)

**Comment by spydmobile** [comment]
@rob is this what you need?

**Comment by spydmobile** [comment]
@RobBryce  You may want the next revision, not sure

**Comment by spydmobile** [comment]
@RobBryce will you be needing any other logos or can I close this as complete?

**Comment by spydmobile** [comment]
Rob needs a new official GNWT Logo for his homepage:
https://heartlandsoftware.ca/

**Comment by spydmobile** [comment]
![GNWT Logo](https://wise-developers.github.io/public_wise_assets/logos/GNWT_Logo.jpeg)
here is the new logo @RobBryce !

**Comment by RobBryce** [comment]
Thanks!
