### ISSUE TITLE
[PSaaS FR]: smarter burning periods

### ISSUE THREAD

**Issue by RobBryce** [WISE-Developers/Project_issues#91]
### Contact Details

rbryce@heartlandsoftware.ca

### What is needed?

Burning conditions include burning periods - start and end times when a fire is expected to burn.  For an interactive tool like Prometheus, it's not hard to set up these settings for a short duration run.  For an automated system, this may be less than ideal where the user may want to plan out for a large area and a long season.

I ask that we consider letting a burning period be a function of sun rise and set, since that seems to be what we're capturing.  For example "let burning start at about 1.5 hours after sun rise, and stop burning at about 20 minutes after sun set".  This wouldn't replace the current hard coded start/end times, but be a mutually exclusive option.  This way, burning periods would automatically adjust through the course of a season, and by location.

### How will this improve the project or tool?

Simpler to set up a burning period for a full season of modelling.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
I 100% agree. For Alaska, Yukon, NWT , and the northern parts of eastern provinces this will be critical, for BA,AB sk etc not so much, but yes, yes yes. Further I would like to bump this awesome idea up in priority.

**Comment by RobBryce** [comment]
After some thought, there’s a few potential approaches here.  Recall that PSaaS (and Prometheus) are event driven, in that values are considered constant until another event occurs.  Events can be introductions of ignitions, new weather, a patch becoming active or inactive, or a burning period time/date setting.
1.)	Let each vertex have its on burning period.  This was the original idea when I posted that, but would need some massaging to actually work, since we don’t want to create a new event during possibly every second while the sun is reaching sun rise or set.  The obvious solution would be set some granularity to the sun rise/set calculations to allow an event every (e.g.) 5 minutes rather than every second.  Time granularity for sun-set and sun-rise could be a parameter with a default value.
2.)	Change granularity from per-vertex to per-fire or per-FGM: Calculate a sun rise/set for all fires, or for each fire individually.  We already have a setting to let fires burn independently of each other until they get close to each other.  Here, the extents of the fire could be calculated and the first vertex to see sun rise, and the last vertex to see sun set, for a simulation or for a fire, could be used as the event.  Or instead of the first/last, we average or take the median of the fire polygon, etc.  The center of the clipped grid data won’t be appropriate.
3.)	If we simply don’t use sun rise and set as an event, then vertices would turn on and off based on these settings and just calculate to the next nearest event.  This would likely capture the (low) accuracy of the model without a lot of influence in performance.  Worst case would have the vertex delay a change in state by up to an hour, since weather has a granularity of an hour.

**Comment by spydmobile** [comment]
@RobBryce Moving forward, I think every new feature should include a unit test Starting with this.

**Comment by nealmcloughlin** [comment]
I like the idea of burning periods applying per vertex. However, I'm not sold on using sunrise and sunset as the burning period parameter. I agree that this is a more dynamic input through an entire fire season than rigid start and end hours.  However, I'm also not a fan of rigid start and end hours. 

When I started my career in fire there was this thing called overnight recovery where temperatures decreased, RH increased, and HFFMC decreased to the point that fire activity stopped. While overnight recovery still occurs, the degree of recovery is often insufficient to stop fire activity. Overnight temperatures are increasing with climate change. Some of the biggest fire runs I observed in western Canada over the last decade are occurring through the night. 

I agree that fire modelling needs to do a better job of defining burning conditions/periods. I don't think sunrise and sunset are the way to do it. I have other ideas we could explore. That said, I like Rob's first suggestion to let each vertex have it's own burning period. This would address large fires where part of the fire is burning and the other half is being rained on.

**Comment by nealmcloughlin** [comment]
Do we have any data or case studies that demonstrate the use of sunrise and sunset for predicting burning periods?

**Comment by spydmobile** [comment]
@nealmcloughlin and @RobBryce I think this will be a feature largely used by folks like KJ and I who are modelling fires in the north of 60 where Diurnal curves suck, As to case studies, I have nothing BUT I would say the justification of this is no weaker than using diurnal curves where they obviously dont work. SO, This is how I would like to see it implemented:
I would like to see it implemented far more simply at the SCENARIO level just like the rest of the burning conditions, per vertex will require more data than we have to produce meaningful results, AND per vertex will destroy performance beyond acceptability IMO. I would like to see it implemented as a choice in the burning conditions time, EG date, time or date , sunrise/sunset, with two config options, a sunset modifier and sunrise modifier accepting +-minutes, this will be the quickest and cheapest to implement with the least amount of impact on existing code. and is a real solution to implement now (in the very next build) , while in the longer range we can examine the feasibility of other smarter, higher resolution solutions.

**Comment by RobBryce** [comment]
I remember what @nealmcloughlin is talking about but we already have some conditions in there - FWI, ISI, RH, etc.  This is (from my perspective) something simpler so that it's easier for somebody to configure a set of simulations over a large area, and over a long duration of time.

**Comment by RobBryce** [comment]
Per-vertex thresholding - like what is done for RH, FWI, ISI - really work well when you have spatial wx modelling turned on.  If you don't have that turned on, then all vertices are using the same weather and conditions.

**Comment by RobBryce** [comment]
Quotation is to provide the same functionality as start/end hours for burning periods, but that are relative to sun rise and sun set, rather than the 24 hour clock.  For now, this will be per-scenario (not per-fire or per vertex), so it's consistent with the current start/end hours w/r to implementation and understanding.

To do this, we need to pick one spot for where sun rise and set will be calculated, and I'll calculate the mean X, Y location for all vertices for all fires.  That's something like a centroid of a polygon, but a bit different to deal with multiple polygons.  Furthermore, I'll also exclude interior perimeters and just calculate the median based on the exterior.

To do this, we need to modify:
- protobuf definitions
- builder, API implementation
- PSaaS I/O
- summary reports from PSaaS
This work will be done in V6 and V7 to assist in V6/V7 comparison testing but will not be added to the Prometheus UI - to avoid that cost.

Quotation covers these modifications, testing, and upload (to here) a test FGMJ used to illustrate the results, along with the summary outputs to show its behaviour.

**Comment by RobBryce** [comment]
Work for this has been tested against a fire far enough south where there is sun rise and set, and also a fire that is far enough north where there's permanent daylight.  Right now, it all seems to work because:

- where there's permanent sunlight, there is no event to trigger a burning conditions event (so burns through the night)
- where there's sunset and sunrise, there are events, and they are calculated relative to sunrise and set

Things could get "interesting" with odd combinations where we transition to/from permanent sunlight AND have drastic changes in relative offsets for burning conditions relative to sun rise and set.

**Comment by spydmobile** [comment]
This will be tested by way of firecast GUI by @spydmobile & @RobBryce
