### ISSUE TITLE
[PSaaS Bug]: Java language library calls not thread safe

### ISSUE THREAD

**Issue by RobBryce** [WISE-Developers/Project_issues#97]
### Contact Details

rbryce@heartlandsoftware.ca

### What happened?

This item is related to #59 but for a different language.  Builder and Manager are both written in Java.  Although the C/C++ libraries have evolved from the 80's and need updating for thread safety, there should also be review of this in the Java code bases.  Basic collection classes (List, Set, Map) are not thread safe.  There are a few other objects which reference static data which do not guarantee thread safety, either.
I'm not expecting any issues to be found but it's worth performing a conscious check on potential obvious issues.

### Version

(Linux) 2021.11.xx

### What component are you seeing the problem on?

Manager

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by spydmobile** [comment]
@RobBryce What is the status of this work please

**Comment by RobBryce** [comment]
This work has been performed.
